design doc
ryanroberson3/MCTracker pull request #1
Opened 2023-10-26 19:31 UTC by ryanroberson3

2023-10-26 22:24 UTC, cpenner461 requested changes
This is a really strong first pass at this - good job. I've left a variety of comments throughout with several things I've seen (don't let the number of comments scare you off!).

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +_**MCTracker** is an app that keeps track of your Marvel Champions collection and logs games for players.
I'd add a brief note about what Marvel Champions is - you don't have to go into a LOT of detail but should include enough so that someone who's not familiar with it will be able to understand what you're building with this.

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +It will allow players to log the Hero they use, the villain they face, whether they won or lost, and what aspect they played in.
re: explaining what Marvel Chamions is, I assume that what aspect you play in makes sense if you know what the game is.

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +## 3. Use Cases
Just a formatting note on these - you don't need to italicize them (wrapping them with \_).

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +U1. _As a [MC player], I want to create a new game log for a MC game that I just played_
Is this only for games that you _just played_ or can you enter logs for a game you played yesterday but forgot to log then? It's fine either way, but depending what you mean by this could impact implementation choices you make.

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +U2. _As a [MC player], I want to view(get) a list of all my game logs_
Small note: we generally leave implementation "details" or terminology out of these - i.e. "view" feels like the better choice here, even though this will end up being a "GET" endpoint.

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +U4. _As a [MC player], I want to update a game log for a MC game_
Can you update all fields or just some of  them? If just some of them you don't necessarily need to identify them all here, but probably worth mentioning that it'd just be a subset of fields.

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +SU1. _As a [MC player], I want to view a list of my favorite heroes_
You probably want a stretch goal before this along the lines of "I want to be able to mark certain heroes as my favorite".

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +- Accepts data to update a gameLog and returns the updated gameLog.
Similar to the note above on the user story - what data will you be able to update?

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +- Accepts `GET` requests to `/gamelogs/:`
typo with the trailing `/:` here

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +- Accepts `GET` requests to `/gamelogs/:`
typo with the `/:` here

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +- Accepts `GET` request to `/gamelogs/:hero`
`:hero` should probably be something like `:heroId`

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +- Accepts `GET` request to `/gamelogs/:villain`
`:villain` should probably be something like `:villainId`

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +- Accepts `GET` request to `/gamelogs/:aspect`
`:aspect` should probably be something like `:aspectId`

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +_Define the DynamoDB tables you will need for the data your service will use. It may be helpful to first think of what
You can clean up/remove the instructions like this one throughout the doc.

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +outcome(w/l) // enum
I think that Dynamo will let you name a field like this but I'd suggest doing something like `outcome_wl` - avoid the parentheses and slashes in field names.

Also while this is an enum in your Java model what will it be in Dynamo?

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +hero // PlayerCharacter
Similar to the enums above, what type will you use to store these in Dynamo?

2023-10-26 22:24 UTC, cpenner461 commented on resources/design-document.md
> +[Link to mock up board with all slides](https://jamboard.google.com/d/1rF50VtNMG0kGWcXDh3yenRobcF1Klmn7RgN8AbX6IkQ/viewer?f=0)
Can you either make this public or give read access to charlie.penner@nashvillesoftwareschool.com?

2023-11-01 20:53 UTC, ryanroberson3 commented on resources/design-document.md
After talking with Jean, I made a few changes to the design. 

Added 3 endpoints: GetAllPlayerCharacters, GetAllAspects, GetAllOutcomes. These will be used for the dropdown menus when the user is creating a game log.

GetAllPlayerCharacters will return all the PlayerCharacters from the playercharacters table. If the role parameter is provided then it will provide all the characters for that role. So for example, all the heroes for the dropdown menu, and all the villains for the dropdown menu.

GetAllAspects & GetAllOutcomes will return all of the enum values for their respective dropdown menu.

Got rid of the PlayerCharacter model since we are only storing strings on there. 
Added the List<String> hero because there could be up to 4 of them to the GameLog model
Added villain with just a string to the GameLog model


Made the Hero, Villain and Aspect the sort key for their GSI's that way it is different from the regular table.


Hope these changes are good!

2023-11-02 00:31 UTC, cpenner461 approved these changes
Thanks for making these changes - I think what you have here is good - I'm approving this.

For future PRs keep them as narrowly focused as you can - this one has some other skeleton code included that ideally would be part of a separate PR. It's fine to keep this one here as-is (don't bother splitting it out).

2023-11-02 15:29 UTC, merged